// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqspwgklsfbcxwnxszqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxc3B3Z2tsc2ZiY3h3bnhzenFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODE4OTYsImV4cCI6MjA2MjI1Nzg5Nn0.giH4L9YA3YlCDSe-xO9JZ8ASA7u9htwaqkK96nuTnW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);